// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB08FOS1Zl-6uF2AWc_0RDVzRI_xDEOnHo',
    appId: '1:370144530594:web:a33c5c0c4447568e7487fb',
    messagingSenderId: '370144530594',
    projectId: 'todolistflutter-b7552',
    authDomain: 'todolistflutter-b7552.firebaseapp.com',
    storageBucket: 'todolistflutter-b7552.appspot.com',
    measurementId: 'G-DXR82W0G1J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk22inFvWCXHU0byYxcg1iWKcbf52s6NU',
    appId: '1:370144530594:android:093112dd8596e40e7487fb',
    messagingSenderId: '370144530594',
    projectId: 'todolistflutter-b7552',
    storageBucket: 'todolistflutter-b7552.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2vqXTPiJVb5iel48aDO3JS9VRt7srk1A',
    appId: '1:370144530594:ios:4fe2f086bfdc68627487fb',
    messagingSenderId: '370144530594',
    projectId: 'todolistflutter-b7552',
    storageBucket: 'todolistflutter-b7552.appspot.com',
    iosBundleId: 'com.example.todolist',
  );
}
